version: "3"

services:
  db_matchlytics:
    image: postgres
    container_name: db_matchlytics
    restart: always
    hostname: "db_matchlytics"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - .env
    command: postgres -p ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  mongo_matchlytics:
    image: mongo
    container_name: mongo_matchlytics
    restart: always
    env_file:
      - .env
    volumes:
      - ./mongo_db:/data/db

  matchlytics_server:
    container_name: matchlytics_server
    env_file:
      - .env
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: "always"
    depends_on:
      - "db_matchlytics"
      - "mongo_matchlytics"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
