version: "3"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    hostname: "oauth_universal_links_db"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"

  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: fs-scrapper-mongo-admin
    #   MONGO_INITDB_ROOT_PASSWORD: Admin!123
    #   MONGO_INITDB_ROOT_PASSWORD: Admin!123
    env_file:
      - .env
    volumes:
      - ./mongo_db:/data/db

  server:
    container_name: server
    env_file:
      - .env
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: "always"
    depends_on:
      - "db"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
